remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: "OmniSci-Lab"
description: "Nhóm nghiên cứu phát triển phần mềm"
title_separator          : "-"
subtitle                 : ""

markdown: kramdown

header_pages:
  - index.md
  - about.md
  - blog.md

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "#"
  since: "2024 - 2025"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - README.md